@baseUrl=https://localhost:7164
@applicationId=test-app

### GET hsg-organization-type
GET {{baseUrl}}/ValueSet/hsg-organization-type
X-Ihis-SourceApplication: {{applicationId}}

### GET hsg-residential-status
GET {{baseUrl}}/ValueSet/hsg-residential-status
X-Ihis-SourceApplication: {{applicationId}}